var areaJson = [
    {
        "Name": "澳门",
        "confIdence": "40",
        "Id": 48,
        "FirstCharacter": "A",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.19297596",
        "level": 3,
        "lon": "113.5496844",
        "parentId": 14,
        "Pinyin": "aomen",
        "precise": "0"
    },
    {
        "Name": "安庆",
        "confIdence": "10",
        "Id": 155,
        "FirstCharacter": "A",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.53789782",
        "level": 3,
        "lon": "117.0587388",
        "parentId": 28,
        "Pinyin": "anqing",
        "precise": "0"
    },
    {
        "Name": "蚌埠",
        "confIdence": "12",
        "Id": 150,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.92949891",
        "level": 3,
        "lon": "117.3570799",
        "parentId": 28,
        "Pinyin": "bangbu",
        "precise": "0"
    },
    {
        "Name": "滁州",
        "confIdence": "10",
        "Id": 157,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.3173506",
        "level": 3,
        "lon": "118.3245704",
        "parentId": 28,
        "Pinyin": "chuzhou",
        "precise": "0"
    },
    {
        "Name": "池州",
        "confIdence": "12",
        "Id": 162,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.66001925",
        "level": 3,
        "lon": "117.4944768",
        "parentId": 28,
        "Pinyin": "chizhou",
        "precise": "0"
    },
    {
        "Name": "阜阳",
        "confIdence": "12",
        "Id": 158,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.90121133",
        "level": 3,
        "lon": "115.8209323",
        "parentId": 28,
        "Pinyin": "fuyang",
        "precise": "0"
    },
    {
        "Name": "合肥",
        "confIdence": "12",
        "Id": 148,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.86694226",
        "level": 3,
        "lon": "117.2826991",
        "parentId": 28,
        "Pinyin": "hefei",
        "precise": "0"
    },
    {
        "Name": "淮南",
        "confIdence": "14",
        "Id": 151,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.64281182",
        "level": 3,
        "lon": "117.0186389",
        "parentId": 28,
        "Pinyin": "huainan",
        "precise": "0"
    },
    {
        "Name": "淮北",
        "confIdence": "14",
        "Id": 153,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.96002331",
        "level": 3,
        "lon": "116.7914474",
        "parentId": 28,
        "Pinyin": "huaibei",
        "precise": "0"
    },
    {
        "Name": "黄山",
        "confIdence": "12",
        "Id": 156,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.73443486",
        "level": 3,
        "lon": "118.2935696",
        "parentId": 28,
        "Pinyin": "huangshan",
        "precise": "0"
    },
    {
        "Name": "六安",
        "confIdence": "10",
        "Id": 160,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.75555836",
        "level": 3,
        "lon": "116.5052527",
        "parentId": 28,
        "Pinyin": "liuan",
        "precise": "0"
    },
    {
        "Name": "马鞍山",
        "confIdence": "14",
        "Id": 152,
        "FirstCharacter": "M",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.68852816",
        "level": 3,
        "lon": "118.5158818",
        "parentId": 28,
        "Pinyin": "maanshan",
        "precise": "0"
    },
    {
        "Name": "宿州",
        "confIdence": "10",
        "Id": 159,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.63677239",
        "level": 3,
        "lon": "116.9886924",
        "parentId": 28,
        "Pinyin": "suzhou",
        "precise": "0"
    },
    {
        "Name": "铜陵",
        "confIdence": "14",
        "Id": 154,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.94092969",
        "level": 3,
        "lon": "117.8194287",
        "parentId": 28,
        "Pinyin": "tongling",
        "precise": "0"
    },
    {
        "Name": "芜湖",
        "confIdence": "14",
        "Id": 149,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.36601979",
        "level": 3,
        "lon": "118.3841084",
        "parentId": 28,
        "Pinyin": "wuhu",
        "precise": "0"
    },
    {
        "Name": "宣城",
        "confIdence": "12",
        "Id": 163,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.95164235",
        "level": 3,
        "lon": "118.7520963",
        "parentId": 28,
        "Pinyin": "xuancheng",
        "precise": "0"
    },
    {
        "Name": "亳州",
        "confIdence": "12",
        "Id": 161,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.87121057",
        "level": 3,
        "lon": "115.7879282",
        "parentId": 28,
        "Pinyin": "zuozhou",
        "precise": "0"
    },
    {
        "Name": "北京",
        "confIdence": "10",
        "Id": 49,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.92998578",
        "level": 3,
        "lon": "116.395645",
        "parentId": 15,
        "Pinyin": "beijing",
        "precise": "0"
    },
    {
        "Name": "福州",
        "confIdence": "10",
        "Id": 164,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.0471255",
        "level": 3,
        "lon": "119.3302211",
        "parentId": 29,
        "Pinyin": "fuzhou",
        "precise": "0"
    },
    {
        "Name": "龙岩",
        "confIdence": "10",
        "Id": 171,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.07868543",
        "level": 3,
        "lon": "117.0179967",
        "parentId": 29,
        "Pinyin": "longyan",
        "precise": "0"
    },
    {
        "Name": "南平",
        "confIdence": "10",
        "Id": 170,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.64362647",
        "level": 3,
        "lon": "118.1818829",
        "parentId": 29,
        "Pinyin": "nanping",
        "precise": "0"
    },
    {
        "Name": "宁德",
        "confIdence": "10",
        "Id": 172,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.65652742",
        "level": 3,
        "lon": "119.5420822",
        "parentId": 29,
        "Pinyin": "ningde",
        "precise": "0"
    },
    {
        "Name": "莆田",
        "confIdence": "12",
        "Id": 166,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.44845014",
        "level": 3,
        "lon": "119.077731",
        "parentId": 29,
        "Pinyin": "putian",
        "precise": "0"
    },
    {
        "Name": "泉州",
        "confIdence": "12",
        "Id": 168,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.90165238",
        "level": 3,
        "lon": "118.6003623",
        "parentId": 29,
        "Pinyin": "quanzhou",
        "precise": "0"
    },
    {
        "Name": "三明",
        "confIdence": "10",
        "Id": 167,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.27083528",
        "level": 3,
        "lon": "117.6421939",
        "parentId": 29,
        "Pinyin": "sanming",
        "precise": "0"
    },
    {
        "Name": "厦门",
        "confIdence": "14",
        "Id": 165,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.48923061",
        "level": 3,
        "lon": "118.103886",
        "parentId": 29,
        "Pinyin": "xiamen",
        "precise": "0"
    },
    {
        "Name": "漳州",
        "confIdence": "12",
        "Id": 169,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.51706478",
        "level": 3,
        "lon": "117.6762047",
        "parentId": 29,
        "Pinyin": "zhangzhou",
        "precise": "0"
    },
    {
        "Name": "潮州",
        "confIdence": "14",
        "Id": 261,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.66181168",
        "level": 3,
        "lon": "116.630076",
        "parentId": 35,
        "Pinyin": "chaozhou",
        "precise": "0"
    },
    {
        "Name": "东莞",
        "confIdence": "14",
        "Id": 259,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.04302382",
        "level": 3,
        "lon": "113.763434",
        "parentId": 35,
        "Pinyin": "dongzuo",
        "precise": "0"
    },
    {
        "Name": "佛山",
        "confIdence": "12",
        "Id": 248,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.03509484",
        "level": 3,
        "lon": "113.1340256",
        "parentId": 35,
        "Pinyin": "foshan",
        "precise": "0"
    },
    {
        "Name": "广州",
        "confIdence": "12",
        "Id": 243,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.1200491",
        "level": 3,
        "lon": "113.3076497",
        "parentId": 35,
        "Pinyin": "guangzhou",
        "precise": "0"
    },
    {
        "Name": "河源",
        "confIdence": "12",
        "Id": 256,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.75725085",
        "level": 3,
        "lon": "114.7137215",
        "parentId": 35,
        "Pinyin": "heyuan",
        "precise": "0"
    },
    {
        "Name": "惠州",
        "confIdence": "12",
        "Id": 253,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.11353985",
        "level": 3,
        "lon": "114.4106581",
        "parentId": 35,
        "Pinyin": "huizhou",
        "precise": "0"
    },
    {
        "Name": "揭阳",
        "confIdence": "12",
        "Id": 262,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.54799947",
        "level": 3,
        "lon": "116.3795009",
        "parentId": 35,
        "Pinyin": "jieyang",
        "precise": "0"
    },
    {
        "Name": "江门",
        "confIdence": "12",
        "Id": 249,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.57511678",
        "level": 3,
        "lon": "113.0781253",
        "parentId": 35,
        "Pinyin": "jiangmen",
        "precise": "0"
    },
    {
        "Name": "茂名",
        "confIdence": "12",
        "Id": 251,
        "FirstCharacter": "M",
        "isFlag": 0,
        "isInland": 0,
        "lan": "21.66822572",
        "level": 3,
        "lon": "110.9312453",
        "parentId": 35,
        "Pinyin": "maoming",
        "precise": "0"
    },
    {
        "Name": "梅州",
        "confIdence": "12",
        "Id": 254,
        "FirstCharacter": "M",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.30457061",
        "level": 3,
        "lon": "116.1264031",
        "parentId": 35,
        "Pinyin": "meizhou",
        "precise": "0"
    },
    {
        "Name": "清远",
        "confIdence": "10",
        "Id": 258,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.69846855",
        "level": 3,
        "lon": "113.0407733",
        "parentId": 35,
        "Pinyin": "qingyuan",
        "precise": "0"
    },
    {
        "Name": "韶关",
        "confIdence": "10",
        "Id": 244,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.80296031",
        "level": 3,
        "lon": "113.5944611",
        "parentId": 35,
        "Pinyin": "shaoguan",
        "precise": "0"
    },
    {
        "Name": "深圳",
        "confIdence": "14",
        "Id": 245,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.54605355",
        "level": 3,
        "lon": "114.0259737",
        "parentId": 35,
        "Pinyin": "shenzuo",
        "precise": "0"
    },
    {
        "Name": "汕头",
        "confIdence": "14",
        "Id": 247,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.38390845",
        "level": 3,
        "lon": "116.7286503",
        "parentId": 35,
        "Pinyin": "shantou",
        "precise": "0"
    },
    {
        "Name": "汕尾",
        "confIdence": "12",
        "Id": 255,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.7787305",
        "level": 3,
        "lon": "115.3729243",
        "parentId": 35,
        "Pinyin": "shanwei",
        "precise": "0"
    },
    {
        "Name": "阳江",
        "confIdence": "12",
        "Id": 257,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "21.8715173",
        "level": 3,
        "lon": "111.9770098",
        "parentId": 35,
        "Pinyin": "yangjiang",
        "precise": "0"
    },
    {
        "Name": "云浮",
        "confIdence": "12",
        "Id": 263,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.93797569",
        "level": 3,
        "lon": "112.050946",
        "parentId": 35,
        "Pinyin": "yunfu",
        "precise": "0"
    },
    {
        "Name": "中山",
        "confIdence": "14",
        "Id": 260,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.54517751",
        "level": 3,
        "lon": "113.42206",
        "parentId": 35,
        "Pinyin": "zhongshan",
        "precise": "0"
    },
    {
        "Name": "珠海",
        "confIdence": "12",
        "Id": 246,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.25691465",
        "level": 3,
        "lon": "113.562447",
        "parentId": 35,
        "Pinyin": "zhuhai",
        "precise": "0"
    },
    {
        "Name": "湛江",
        "confIdence": "12",
        "Id": 250,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "21.2574631",
        "level": 3,
        "lon": "110.3650673",
        "parentId": 35,
        "Pinyin": "zhanjiang",
        "precise": "0"
    },
    {
        "Name": "肇庆",
        "confIdence": "12",
        "Id": 252,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.07866328",
        "level": 3,
        "lon": "112.4796534",
        "parentId": 35,
        "Pinyin": "zhaoqing",
        "precise": "0"
    },
    {
        "Name": "北海",
        "confIdence": "12",
        "Id": 268,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "21.47271824",
        "level": 3,
        "lon": "109.1226279",
        "parentId": 36,
        "Pinyin": "beihai",
        "precise": "0"
    },
    {
        "Name": "百色",
        "confIdence": "10",
        "Id": 273,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.90151237",
        "level": 3,
        "lon": "106.6318214",
        "parentId": 36,
        "Pinyin": "baise",
        "precise": "0"
    },
    {
        "Name": "崇左",
        "confIdence": "12",
        "Id": 277,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.4154553",
        "level": 3,
        "lon": "107.357322",
        "parentId": 36,
        "Pinyin": "chongzuo",
        "precise": "0"
    },
    {
        "Name": "防城港",
        "confIdence": "12",
        "Id": 269,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "21.61739847",
        "level": 3,
        "lon": "108.3517912",
        "parentId": 36,
        "Pinyin": "fangchenggang",
        "precise": "0"
    },
    {
        "Name": "桂林",
        "confIdence": "10",
        "Id": 266,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.26290125",
        "level": 3,
        "lon": "110.2609201",
        "parentId": 36,
        "Pinyin": "guilin",
        "precise": "0"
    },
    {
        "Name": "贵港",
        "confIdence": "12",
        "Id": 271,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.10337316",
        "level": 3,
        "lon": "109.6137076",
        "parentId": 36,
        "Pinyin": "guigang",
        "precise": "0"
    },
    {
        "Name": "贺州",
        "confIdence": "12",
        "Id": 274,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.41105355",
        "level": 3,
        "lon": "111.5525942",
        "parentId": 36,
        "Pinyin": "hezhou",
        "precise": "0"
    },
    {
        "Name": "河池",
        "confIdence": "10",
        "Id": 275,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.69952078",
        "level": 3,
        "lon": "108.0699477",
        "parentId": 36,
        "Pinyin": "hechi",
        "precise": "0"
    },
    {
        "Name": "柳州",
        "confIdence": "10",
        "Id": 265,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.32905335",
        "level": 3,
        "lon": "109.4224018",
        "parentId": 36,
        "Pinyin": "liuzhou",
        "precise": "0"
    },
    {
        "Name": "来宾",
        "confIdence": "12",
        "Id": 276,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.74116593",
        "level": 3,
        "lon": "109.2318165",
        "parentId": 36,
        "Pinyin": "laibin",
        "precise": "0"
    },
    {
        "Name": "南宁",
        "confIdence": "10",
        "Id": 264,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.80649294",
        "level": 3,
        "lon": "108.2972336",
        "parentId": 36,
        "Pinyin": "nanning",
        "precise": "0"
    },
    {
        "Name": "钦州",
        "confIdence": "12",
        "Id": 270,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "21.97335047",
        "level": 3,
        "lon": "108.6387981",
        "parentId": 36,
        "Pinyin": "qinzhou",
        "precise": "0"
    },
    {
        "Name": "梧州",
        "confIdence": "12",
        "Id": 267,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.48539464",
        "level": 3,
        "lon": "111.305472",
        "parentId": 36,
        "Pinyin": "wuzhou",
        "precise": "0"
    },
    {
        "Name": "玉林",
        "confIdence": "12",
        "Id": 272,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.64397361",
        "level": 3,
        "lon": "110.1516763",
        "parentId": 36,
        "Pinyin": "yulin",
        "precise": "0"
    },
    {
        "Name": "安顺",
        "confIdence": "12",
        "Id": 303,
        "FirstCharacter": "A",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.22859458",
        "level": 3,
        "lon": "105.92827",
        "parentId": 39,
        "Pinyin": "anshun",
        "precise": "0"
    },
    {
        "Name": "毕节",
        "confIdence": "12",
        "Id": 304,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.40856213",
        "level": 3,
        "lon": "105.3333234",
        "parentId": 39,
        "Pinyin": "bijie",
        "precise": "0"
    },
    {
        "Name": "贵阳",
        "confIdence": "12",
        "Id": 300,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.62990674",
        "level": 3,
        "lon": "106.7091771",
        "parentId": 39,
        "Pinyin": "guiyang",
        "precise": "0"
    },
    {
        "Name": "六盘水",
        "confIdence": "12",
        "Id": 301,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.59186606",
        "level": 3,
        "lon": "104.8520868",
        "parentId": 39,
        "Pinyin": "liupanshui",
        "precise": "0"
    },
    {
        "Name": "铜仁",
        "confIdence": "14",
        "Id": 305,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.67490269",
        "level": 3,
        "lon": "109.168558",
        "parentId": 39,
        "Pinyin": "tongren",
        "precise": "0"
    },
    {
        "Name": "遵义",
        "confIdence": "10",
        "Id": 302,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.69996138",
        "level": 3,
        "lon": "106.9312603",
        "parentId": 39,
        "Pinyin": "zunyi",
        "precise": "0"
    },
    {
        "Name": "白银",
        "confIdence": "10",
        "Id": 332,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.54668171",
        "level": 3,
        "lon": "104.1712409",
        "parentId": 43,
        "Pinyin": "baiyin",
        "precise": "0"
    },
    {
        "Name": "定西",
        "confIdence": "10",
        "Id": 339,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.58605624",
        "level": 3,
        "lon": "104.6266376",
        "parentId": 43,
        "Pinyin": "dingxi",
        "precise": "0"
    },
    {
        "Name": "嘉峪关",
        "confIdence": "14",
        "Id": 330,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.80239733",
        "level": 3,
        "lon": "98.28163459",
        "parentId": 43,
        "Pinyin": "jiayuguan",
        "precise": "0"
    },
    {
        "Name": "金昌",
        "confIdence": "12",
        "Id": 331,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.5160718",
        "level": 3,
        "lon": "102.2081263",
        "parentId": 43,
        "Pinyin": "jinchang",
        "precise": "0"
    },
    {
        "Name": "酒泉",
        "confIdence": "0",
        "Id": 337,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.74147377",
        "level": 3,
        "lon": "98.50841451",
        "parentId": 43,
        "Pinyin": "jiuquan",
        "precise": "0"
    },
    {
        "Name": "兰州",
        "confIdence": "10",
        "Id": 329,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.06422553",
        "level": 3,
        "lon": "103.8233054",
        "parentId": 43,
        "Pinyin": "lanzhou",
        "precise": "0"
    },
    {
        "Name": "陇南",
        "confIdence": "10",
        "Id": 340,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.39447997",
        "level": 3,
        "lon": "104.9345734",
        "parentId": 43,
        "Pinyin": "longnan",
        "precise": "0"
    },
    {
        "Name": "平凉",
        "confIdence": "12",
        "Id": 336,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.55011019",
        "level": 3,
        "lon": "106.6889112",
        "parentId": 43,
        "Pinyin": "pingliang",
        "precise": "0"
    },
    {
        "Name": "庆阳",
        "confIdence": "10",
        "Id": 338,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.72680075",
        "level": 3,
        "lon": "107.6442271",
        "parentId": 43,
        "Pinyin": "qingyang",
        "precise": "0"
    },
    {
        "Name": "天水",
        "confIdence": "12",
        "Id": 333,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.58431942",
        "level": 3,
        "lon": "105.7369316",
        "parentId": 43,
        "Pinyin": "tianshui",
        "precise": "0"
    },
    {
        "Name": "武威",
        "confIdence": "10",
        "Id": 334,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.93317214",
        "level": 3,
        "lon": "102.6401473",
        "parentId": 43,
        "Pinyin": "wuwei",
        "precise": "0"
    },
    {
        "Name": "张掖",
        "confIdence": "10",
        "Id": 335,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.9393203",
        "level": 3,
        "lon": "100.4598919",
        "parentId": 43,
        "Pinyin": "zhangye",
        "precise": "0"
    },
    {
        "Name": "保定",
        "confIdence": "10",
        "Id": 64,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.88656455",
        "level": 3,
        "lon": "115.4948102",
        "parentId": 20,
        "Pinyin": "baoding",
        "precise": "0"
    },
    {
        "Name": "承德",
        "confIdence": "10",
        "Id": 66,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.99252105",
        "level": 3,
        "lon": "117.9338225",
        "parentId": 20,
        "Pinyin": "chengde",
        "precise": "0"
    },
    {
        "Name": "沧州",
        "confIdence": "10",
        "Id": 67,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.29761535",
        "level": 3,
        "lon": "116.8638065",
        "parentId": 20,
        "Pinyin": "cangzhou",
        "precise": "0"
    },
    {
        "Name": "邯郸",
        "confIdence": "12",
        "Id": 62,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.60930793",
        "level": 3,
        "lon": "114.4826939",
        "parentId": 20,
        "Pinyin": "handan",
        "precise": "0"
    },
    {
        "Name": "衡水",
        "confIdence": "12",
        "Id": 69,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.74692905",
        "level": 3,
        "lon": "115.6862287",
        "parentId": 20,
        "Pinyin": "hengshui",
        "precise": "0"
    },
    {
        "Name": "廊坊",
        "confIdence": "12",
        "Id": 68,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.51861063",
        "level": 3,
        "lon": "116.7036022",
        "parentId": 20,
        "Pinyin": "langfang",
        "precise": "0"
    },
    {
        "Name": "秦皇岛",
        "confIdence": "12",
        "Id": 61,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.94546157",
        "level": 3,
        "lon": "119.6043676",
        "parentId": 20,
        "Pinyin": "qinhuangdao",
        "precise": "0"
    },
    {
        "Name": "石家庄",
        "confIdence": "10",
        "Id": 59,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.04895831",
        "level": 3,
        "lon": "114.5220818",
        "parentId": 20,
        "Pinyin": "shijiazhuang",
        "precise": "0"
    },
    {
        "Name": "唐山",
        "confIdence": "10",
        "Id": 60,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.65053092",
        "level": 3,
        "lon": "118.1834506",
        "parentId": 20,
        "Pinyin": "tangshan",
        "precise": "0"
    },
    {
        "Name": "邢台",
        "confIdence": "12",
        "Id": 63,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.0695312",
        "level": 3,
        "lon": "114.5204868",
        "parentId": 20,
        "Pinyin": "xingtai",
        "precise": "0"
    },
    {
        "Name": "张家口",
        "confIdence": "10",
        "Id": 65,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.81118849",
        "level": 3,
        "lon": "114.8937815",
        "parentId": 20,
        "Pinyin": "zhangjiakou",
        "precise": "0"
    },
    {
        "Name": "大庆",
        "confIdence": "10",
        "Id": 117,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "46.59670902",
        "level": 3,
        "lon": "125.0218397",
        "parentId": 25,
        "Pinyin": "daqing",
        "precise": "0"
    },
    {
        "Name": "哈尔滨",
        "confIdence": "10",
        "Id": 112,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "45.77322463",
        "level": 3,
        "lon": "126.6577169",
        "parentId": 25,
        "Pinyin": "haerbin",
        "precise": "0"
    },
    {
        "Name": "鹤岗",
        "confIdence": "10",
        "Id": 115,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "47.3386659",
        "level": 3,
        "lon": "130.2924721",
        "parentId": 25,
        "Pinyin": "hegang",
        "precise": "0"
    },
    {
        "Name": "黑河",
        "confIdence": "0",
        "Id": 122,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "50.25069009",
        "level": 3,
        "lon": "127.5008303",
        "parentId": 25,
        "Pinyin": "heihe",
        "precise": "0"
    },
    {
        "Name": "鸡西",
        "confIdence": "10",
        "Id": 114,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "45.32153989",
        "level": 3,
        "lon": "130.9417673",
        "parentId": 25,
        "Pinyin": "jixi",
        "precise": "0"
    },
    {
        "Name": "佳木斯",
        "confIdence": "0",
        "Id": 119,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "46.8137796",
        "level": 3,
        "lon": "130.2847346",
        "parentId": 25,
        "Pinyin": "jiamusi",
        "precise": "0"
    },
    {
        "Name": "牡丹江",
        "confIdence": "10",
        "Id": 121,
        "FirstCharacter": "M",
        "isFlag": 0,
        "isInland": 0,
        "lan": "44.58852115",
        "level": 3,
        "lon": "129.6080354",
        "parentId": 25,
        "Pinyin": "mudanjiang",
        "precise": "0"
    },
    {
        "Name": "齐齐哈尔",
        "confIdence": "10",
        "Id": 113,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "47.34769981",
        "level": 3,
        "lon": "123.9872889",
        "parentId": 25,
        "Pinyin": "qiqihaer",
        "precise": "0"
    },
    {
        "Name": "七台河",
        "confIdence": "12",
        "Id": 120,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "45.77500537",
        "level": 3,
        "lon": "131.019048",
        "parentId": 25,
        "Pinyin": "qitaihe",
        "precise": "0"
    },
    {
        "Name": "双鸭山",
        "confIdence": "10",
        "Id": 116,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "46.65510206",
        "level": 3,
        "lon": "131.1714017",
        "parentId": 25,
        "Pinyin": "shuangyashan",
        "precise": "0"
    },
    {
        "Name": "绥化",
        "confIdence": "10",
        "Id": 123,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "46.64606393",
        "level": 3,
        "lon": "126.9890946",
        "parentId": 25,
        "Pinyin": "suihua",
        "precise": "0"
    },
    {
        "Name": "伊春",
        "confIdence": "10",
        "Id": 118,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "47.73468508",
        "level": 3,
        "lon": "128.910766",
        "parentId": 25,
        "Pinyin": "yichun",
        "precise": "0"
    },
    {
        "Name": "安阳",
        "confIdence": "12",
        "Id": 205,
        "FirstCharacter": "A",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.11026672",
        "level": 3,
        "lon": "114.3518065",
        "parentId": 32,
        "Pinyin": "anyang",
        "precise": "0"
    },
    {
        "Name": "鹤壁",
        "confIdence": "14",
        "Id": 206,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.75542587",
        "level": 3,
        "lon": "114.2977698",
        "parentId": 32,
        "Pinyin": "hebi",
        "precise": "0"
    },
    {
        "Name": "焦作",
        "confIdence": "12",
        "Id": 208,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.23460756",
        "level": 3,
        "lon": "113.2118359",
        "parentId": 32,
        "Pinyin": "jiaozuo",
        "precise": "0"
    },
    {
        "Name": "开封",
        "confIdence": "12",
        "Id": 202,
        "FirstCharacter": "K",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.80185418",
        "level": 3,
        "lon": "114.3516421",
        "parentId": 32,
        "Pinyin": "kaifeng",
        "precise": "0"
    },
    {
        "Name": "洛阳",
        "confIdence": "10",
        "Id": 203,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.65736782",
        "level": 3,
        "lon": "112.4475248",
        "parentId": 32,
        "Pinyin": "luoyang",
        "precise": "0"
    },
    {
        "Name": "南阳",
        "confIdence": "10",
        "Id": 213,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.01141957",
        "level": 3,
        "lon": "112.5428419",
        "parentId": 32,
        "Pinyin": "nanyang",
        "precise": "0"
    },
    {
        "Name": "平顶山",
        "confIdence": "12",
        "Id": 204,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.74530146",
        "level": 3,
        "lon": "113.300849",
        "parentId": 32,
        "Pinyin": "pingdingshan",
        "precise": "0"
    },
    {
        "Name": "三门峡",
        "confIdence": "12",
        "Id": 212,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.78331994",
        "level": 3,
        "lon": "111.1812621",
        "parentId": 32,
        "Pinyin": "sanmenxia",
        "precise": "0"
    },
    {
        "Name": "商丘",
        "confIdence": "12",
        "Id": 214,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.43858864",
        "level": 3,
        "lon": "115.6418857",
        "parentId": 32,
        "Pinyin": "shangqiu",
        "precise": "0"
    },
    {
        "Name": "新乡",
        "confIdence": "12",
        "Id": 207,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.30725756",
        "level": 3,
        "lon": "113.9126902",
        "parentId": 32,
        "Pinyin": "xinxiang",
        "precise": "0"
    },
    {
        "Name": "许昌",
        "confIdence": "12",
        "Id": 210,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.02673959",
        "level": 3,
        "lon": "113.8353125",
        "parentId": 32,
        "Pinyin": "xuchang",
        "precise": "0"
    },
    {
        "Name": "信阳",
        "confIdence": "10",
        "Id": 216,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.12858231",
        "level": 3,
        "lon": "114.085491",
        "parentId": 32,
        "Pinyin": "xinyang",
        "precise": "0"
    },
    {
        "Name": "郑州",
        "confIdence": "12",
        "Id": 201,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.75661006",
        "level": 3,
        "lon": "113.6496439",
        "parentId": 32,
        "Pinyin": "zhengzhou",
        "precise": "0"
    },
    {
        "Name": "濮阳",
        "confIdence": "12",
        "Id": 209,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.75329789",
        "level": 3,
        "lon": "115.0266274",
        "parentId": 32,
        "Pinyin": "zuoyang",
        "precise": "0"
    },
    {
        "Name": "漯河",
        "confIdence": "14",
        "Id": 211,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.57627869",
        "level": 3,
        "lon": "114.0460614",
        "parentId": 32,
        "Pinyin": "zuohe",
        "precise": "0"
    },
    {
        "Name": "周口",
        "confIdence": "12",
        "Id": 215,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.62374082",
        "level": 3,
        "lon": "114.6541019",
        "parentId": 32,
        "Pinyin": "zhoukou",
        "precise": "0"
    },
    {
        "Name": "驻马店",
        "confIdence": "12",
        "Id": 217,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.98315815",
        "level": 3,
        "lon": "114.0491535",
        "parentId": 32,
        "Pinyin": "zhumadian",
        "precise": "0"
    },
    {
        "Name": "鄂州",
        "confIdence": "14",
        "Id": 225,
        "FirstCharacter": "E",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.38443932",
        "level": 3,
        "lon": "114.895594",
        "parentId": 33,
        "Pinyin": "ezhou",
        "precise": "0"
    },
    {
        "Name": "黄石",
        "confIdence": "12",
        "Id": 219,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.21612713",
        "level": 3,
        "lon": "115.0506832",
        "parentId": 33,
        "Pinyin": "huangshi",
        "precise": "0"
    },
    {
        "Name": "黄冈",
        "confIdence": "10",
        "Id": 227,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.44610894",
        "level": 3,
        "lon": "114.906618",
        "parentId": 33,
        "Pinyin": "huanggang",
        "precise": "0"
    },
    {
        "Name": "荆州",
        "confIdence": "10",
        "Id": 223,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.33259052",
        "level": 3,
        "lon": "112.2418658",
        "parentId": 33,
        "Pinyin": "jingzhou",
        "precise": "0"
    },
    {
        "Name": "荆门",
        "confIdence": "12",
        "Id": 224,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.0426112",
        "level": 3,
        "lon": "112.2173303",
        "parentId": 33,
        "Pinyin": "jingmen",
        "precise": "0"
    },
    {
        "Name": "十堰",
        "confIdence": "10",
        "Id": 220,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.63699434",
        "level": 3,
        "lon": "110.8012289",
        "parentId": 33,
        "Pinyin": "shiyan",
        "precise": "0"
    },
    {
        "Name": "随州",
        "confIdence": "12",
        "Id": 229,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.71785761",
        "level": 3,
        "lon": "113.3793584",
        "parentId": 33,
        "Pinyin": "suizhou",
        "precise": "0"
    },
    {
        "Name": "武汉",
        "confIdence": "12",
        "Id": 218,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.58108413",
        "level": 3,
        "lon": "114.3162001",
        "parentId": 33,
        "Pinyin": "wuhan",
        "precise": "0"
    },
    {
        "Name": "襄阳",
        "confIdence": "14",
        "Id": 222,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.22916859",
        "level": 3,
        "lon": "112.2500928",
        "parentId": 33,
        "Pinyin": "xiangyang",
        "precise": "0"
    },
    {
        "Name": "孝感",
        "confIdence": "12",
        "Id": 226,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.92795478",
        "level": 3,
        "lon": "113.9357344",
        "parentId": 33,
        "Pinyin": "xiaogan",
        "precise": "0"
    },
    {
        "Name": "咸宁",
        "confIdence": "12",
        "Id": 228,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.88065676",
        "level": 3,
        "lon": "114.3000606",
        "parentId": 33,
        "Pinyin": "xianning",
        "precise": "0"
    },
    {
        "Name": "宜昌",
        "confIdence": "10",
        "Id": 221,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.73275782",
        "level": 3,
        "lon": "111.3109811",
        "parentId": 33,
        "Pinyin": "yichang",
        "precise": "0"
    },
    {
        "Name": "长沙",
        "confIdence": "12",
        "Id": 230,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.21347823",
        "level": 3,
        "lon": "112.9793528",
        "parentId": 34,
        "Pinyin": "changsha",
        "precise": "0"
    },
    {
        "Name": "常德",
        "confIdence": "10",
        "Id": 236,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.01214886",
        "level": 3,
        "lon": "111.6537181",
        "parentId": 34,
        "Pinyin": "changde",
        "precise": "0"
    },
    {
        "Name": "郴州",
        "confIdence": "10",
        "Id": 239,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.78226398",
        "level": 3,
        "lon": "113.0377045",
        "parentId": 34,
        "Pinyin": "chenzhou",
        "precise": "0"
    },
    {
        "Name": "衡阳",
        "confIdence": "12",
        "Id": 233,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.89816442",
        "level": 3,
        "lon": "112.5838188",
        "parentId": 34,
        "Pinyin": "hengyang",
        "precise": "0"
    },
    {
        "Name": "怀化",
        "confIdence": "10",
        "Id": 241,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.5574829",
        "level": 3,
        "lon": "109.9869588",
        "parentId": 34,
        "Pinyin": "huaihua",
        "precise": "0"
    },
    {
        "Name": "娄底",
        "confIdence": "12",
        "Id": 242,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.7410733",
        "level": 3,
        "lon": "111.9963964",
        "parentId": 34,
        "Pinyin": "loudi",
        "precise": "0"
    },
    {
        "Name": "邵阳",
        "confIdence": "10",
        "Id": 234,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.23681124",
        "level": 3,
        "lon": "111.4615254",
        "parentId": 34,
        "Pinyin": "shaoyang",
        "precise": "0"
    },
    {
        "Name": "湘潭",
        "confIdence": "12",
        "Id": 232,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.83509505",
        "level": 3,
        "lon": "112.9355556",
        "parentId": 34,
        "Pinyin": "xiangtan",
        "precise": "0"
    },
    {
        "Name": "岳阳",
        "confIdence": "12",
        "Id": 235,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.37800708",
        "level": 3,
        "lon": "113.1461955",
        "parentId": 34,
        "Pinyin": "yueyang",
        "precise": "0"
    },
    {
        "Name": "益阳",
        "confIdence": "10",
        "Id": 238,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.58808778",
        "level": 3,
        "lon": "112.3665466",
        "parentId": 34,
        "Pinyin": "yiyang",
        "precise": "0"
    },
    {
        "Name": "永州",
        "confIdence": "10",
        "Id": 240,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.43597165",
        "level": 3,
        "lon": "111.6146477",
        "parentId": 34,
        "Pinyin": "yongzhou",
        "precise": "0"
    },
    {
        "Name": "株洲",
        "confIdence": "12",
        "Id": 231,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.82743293",
        "level": 3,
        "lon": "113.1316953",
        "parentId": 34,
        "Pinyin": "zhuzhou",
        "precise": "0"
    },
    {
        "Name": "张家界",
        "confIdence": "12",
        "Id": 237,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.12488935",
        "level": 3,
        "lon": "110.4816202",
        "parentId": 34,
        "Pinyin": "zhangjiajie",
        "precise": "0"
    },
    {
        "Name": "海口",
        "confIdence": "14",
        "Id": 278,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "20.02207128",
        "level": 3,
        "lon": "110.3308018",
        "parentId": 37,
        "Pinyin": "haikou",
        "precise": "0"
    },
    {
        "Name": "三亚",
        "confIdence": "14",
        "Id": 279,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "18.25777591",
        "level": 3,
        "lon": "109.5227713",
        "parentId": 37,
        "Pinyin": "sanya",
        "precise": "0"
    },
    {
        "Name": "三沙",
        "confIdence": "-1",
        "Id": 280,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "16.840414",
        "level": 3,
        "lon": "112.347629",
        "parentId": 37,
        "Pinyin": "sansha",
        "precise": "-1"
    },
    {
        "Name": "儋州",
        "confIdence": "14",
        "Id": 281,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "19.57115309",
        "level": 3,
        "lon": "109.4139731",
        "parentId": 37,
        "Pinyin": "zuozhou",
        "precise": "0"
    },
    {
        "Name": "白山",
        "confIdence": "10",
        "Id": 109,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.9458594",
        "level": 3,
        "lon": "126.4357977",
        "parentId": 24,
        "Pinyin": "baishan",
        "precise": "0"
    },
    {
        "Name": "白城",
        "confIdence": "10",
        "Id": 111,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "45.62108628",
        "level": 3,
        "lon": "122.8407767",
        "parentId": 24,
        "Pinyin": "baicheng",
        "precise": "0"
    },
    {
        "Name": "长春",
        "confIdence": "10",
        "Id": 104,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "43.89833761",
        "level": 3,
        "lon": "125.3136424",
        "parentId": 24,
        "Pinyin": "changchun",
        "precise": "0"
    },
    {
        "Name": "吉林",
        "confIdence": "10",
        "Id": 105,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "43.87198833",
        "level": 3,
        "lon": "126.564544",
        "parentId": 24,
        "Pinyin": "jilin",
        "precise": "0"
    },
    {
        "Name": "辽源",
        "confIdence": "12",
        "Id": 107,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "42.92330262",
        "level": 3,
        "lon": "125.1336861",
        "parentId": 24,
        "Pinyin": "liaoyuan",
        "precise": "0"
    },
    {
        "Name": "四平",
        "confIdence": "10",
        "Id": 106,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "43.1755247",
        "level": 3,
        "lon": "124.3913821",
        "parentId": 24,
        "Pinyin": "siping",
        "precise": "0"
    },
    {
        "Name": "松原",
        "confIdence": "10",
        "Id": 110,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "45.13604897",
        "level": 3,
        "lon": "124.8329945",
        "parentId": 24,
        "Pinyin": "songyuan",
        "precise": "0"
    },
    {
        "Name": "通化",
        "confIdence": "10",
        "Id": 108,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.73639713",
        "level": 3,
        "lon": "125.9426501",
        "parentId": 24,
        "Pinyin": "tonghua",
        "precise": "0"
    },
    {
        "Name": "常州",
        "confIdence": "12",
        "Id": 127,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.77139674",
        "level": 3,
        "lon": "119.981861",
        "parentId": 26,
        "Pinyin": "changzhou",
        "precise": "0"
    },
    {
        "Name": "淮安",
        "confIdence": "12",
        "Id": 131,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.60651274",
        "level": 3,
        "lon": "119.0301864",
        "parentId": 26,
        "Pinyin": "huaian",
        "precise": "0"
    },
    {
        "Name": "连云港",
        "confIdence": "12",
        "Id": 130,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.60154897",
        "level": 3,
        "lon": "119.1738722",
        "parentId": 26,
        "Pinyin": "lianyungang",
        "precise": "0"
    },
    {
        "Name": "南京",
        "confIdence": "12",
        "Id": 124,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.0572355",
        "level": 3,
        "lon": "118.7780744",
        "parentId": 26,
        "Pinyin": "nanjing",
        "precise": "0"
    },
    {
        "Name": "南通",
        "confIdence": "12",
        "Id": 129,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.01466454",
        "level": 3,
        "lon": "120.873801",
        "parentId": 26,
        "Pinyin": "nantong",
        "precise": "0"
    },
    {
        "Name": "苏州",
        "confIdence": "12",
        "Id": 128,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.31798737",
        "level": 3,
        "lon": "120.6199071",
        "parentId": 26,
        "Pinyin": "suzhou",
        "precise": "0"
    },
    {
        "Name": "宿迁",
        "confIdence": "12",
        "Id": 136,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.95204973",
        "level": 3,
        "lon": "118.2968934",
        "parentId": 26,
        "Pinyin": "suqian",
        "precise": "0"
    },
    {
        "Name": "泰州",
        "confIdence": "12",
        "Id": 135,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.47605327",
        "level": 3,
        "lon": "119.919606",
        "parentId": 26,
        "Pinyin": "taizhou",
        "precise": "0"
    },
    {
        "Name": "无锡",
        "confIdence": "12",
        "Id": 125,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.57003745",
        "level": 3,
        "lon": "120.3054559",
        "parentId": 26,
        "Pinyin": "wuxi",
        "precise": "0"
    },
    {
        "Name": "徐州",
        "confIdence": "10",
        "Id": 126,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.27155343",
        "level": 3,
        "lon": "117.1881066",
        "parentId": 26,
        "Pinyin": "xuzhou",
        "precise": "0"
    },
    {
        "Name": "盐城",
        "confIdence": "10",
        "Id": 132,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.37986188",
        "level": 3,
        "lon": "120.1488718",
        "parentId": 26,
        "Pinyin": "yancheng",
        "precise": "0"
    },
    {
        "Name": "扬州",
        "confIdence": "12",
        "Id": 133,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.40850525",
        "level": 3,
        "lon": "119.4277776",
        "parentId": 26,
        "Pinyin": "yangzhou",
        "precise": "0"
    },
    {
        "Name": "镇江",
        "confIdence": "12",
        "Id": 134,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.20440944",
        "level": 3,
        "lon": "119.4558354",
        "parentId": 26,
        "Pinyin": "zhenjiang",
        "precise": "0"
    },
    {
        "Name": "抚州",
        "confIdence": "10",
        "Id": 182,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.95454517",
        "level": 3,
        "lon": "116.3609189",
        "parentId": 30,
        "Pinyin": "fuzhou",
        "precise": "0"
    },
    {
        "Name": "赣州",
        "confIdence": "10",
        "Id": 179,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.84529554",
        "level": 3,
        "lon": "114.9359091",
        "parentId": 30,
        "Pinyin": "ganzhou",
        "precise": "0"
    },
    {
        "Name": "景德镇",
        "confIdence": "12",
        "Id": 174,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.30356277",
        "level": 3,
        "lon": "117.1865226",
        "parentId": 30,
        "Pinyin": "jingdezhen",
        "precise": "0"
    },
    {
        "Name": "九江",
        "confIdence": "10",
        "Id": 176,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.71963953",
        "level": 3,
        "lon": "115.999848",
        "parentId": 30,
        "Pinyin": "jiujiang",
        "precise": "0"
    },
    {
        "Name": "吉安",
        "confIdence": "10",
        "Id": 180,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.11384765",
        "level": 3,
        "lon": "114.9920387",
        "parentId": 30,
        "Pinyin": "jian",
        "precise": "0"
    },
    {
        "Name": "南昌",
        "confIdence": "12",
        "Id": 173,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.689578",
        "level": 3,
        "lon": "115.8935275",
        "parentId": 30,
        "Pinyin": "nanchang",
        "precise": "0"
    },
    {
        "Name": "萍乡",
        "confIdence": "12",
        "Id": 175,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.63954422",
        "level": 3,
        "lon": "113.859917",
        "parentId": 30,
        "Pinyin": "pingxiang",
        "precise": "0"
    },
    {
        "Name": "上饶",
        "confIdence": "10",
        "Id": 183,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.45762255",
        "level": 3,
        "lon": "117.9554639",
        "parentId": 30,
        "Pinyin": "shangrao",
        "precise": "0"
    },
    {
        "Name": "新余",
        "confIdence": "14",
        "Id": 177,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.82232156",
        "level": 3,
        "lon": "114.9471174",
        "parentId": 30,
        "Pinyin": "xinyu",
        "precise": "0"
    },
    {
        "Name": "鹰潭",
        "confIdence": "14",
        "Id": 178,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.2413096",
        "level": 3,
        "lon": "117.0354502",
        "parentId": 30,
        "Pinyin": "yingtan",
        "precise": "0"
    },
    {
        "Name": "宜春",
        "confIdence": "10",
        "Id": 181,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.8111299",
        "level": 3,
        "lon": "114.4000387",
        "parentId": 30,
        "Pinyin": "yichun",
        "precise": "0"
    },
    {
        "Name": "鞍山",
        "confIdence": "10",
        "Id": 92,
        "FirstCharacter": "A",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.11874368",
        "level": 3,
        "lon": "123.0077633",
        "parentId": 23,
        "Pinyin": "anshan",
        "precise": "0"
    },
    {
        "Name": "本溪",
        "confIdence": "12",
        "Id": 94,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.32583763",
        "level": 3,
        "lon": "123.7780624",
        "parentId": 23,
        "Pinyin": "benxi",
        "precise": "0"
    },
    {
        "Name": "朝阳",
        "confIdence": "10",
        "Id": 102,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.57182767",
        "level": 3,
        "lon": "120.4461627",
        "parentId": 23,
        "Pinyin": "chaoyang",
        "precise": "0"
    },
    {
        "Name": "大连",
        "confIdence": "10",
        "Id": 91,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.94870994",
        "level": 3,
        "lon": "121.5934778",
        "parentId": 23,
        "Pinyin": "dalian",
        "precise": "0"
    },
    {
        "Name": "丹东",
        "confIdence": "10",
        "Id": 95,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.12902283",
        "level": 3,
        "lon": "124.3385431",
        "parentId": 23,
        "Pinyin": "dandong",
        "precise": "0"
    },
    {
        "Name": "抚顺",
        "confIdence": "12",
        "Id": 93,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.87730383",
        "level": 3,
        "lon": "123.9298198",
        "parentId": 23,
        "Pinyin": "fushun",
        "precise": "0"
    },
    {
        "Name": "阜新",
        "confIdence": "12",
        "Id": 98,
        "FirstCharacter": "F",
        "isFlag": 0,
        "isInland": 0,
        "lan": "42.01925011",
        "level": 3,
        "lon": "121.6608221",
        "parentId": 23,
        "Pinyin": "fuxin",
        "precise": "0"
    },
    {
        "Name": "葫芦岛",
        "confIdence": "12",
        "Id": 103,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.74302988",
        "level": 3,
        "lon": "120.8607576",
        "parentId": 23,
        "Pinyin": "huludao",
        "precise": "0"
    },
    {
        "Name": "锦州",
        "confIdence": "10",
        "Id": 96,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.13087888",
        "level": 3,
        "lon": "121.1477487",
        "parentId": 23,
        "Pinyin": "jinzhou",
        "precise": "0"
    },
    {
        "Name": "辽阳",
        "confIdence": "12",
        "Id": 99,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.27333927",
        "level": 3,
        "lon": "123.1724512",
        "parentId": 23,
        "Pinyin": "liaoyang",
        "precise": "0"
    },
    {
        "Name": "盘锦",
        "confIdence": "12",
        "Id": 100,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.14124802",
        "level": 3,
        "lon": "122.0732278",
        "parentId": 23,
        "Pinyin": "panjin",
        "precise": "0"
    },
    {
        "Name": "沈阳",
        "confIdence": "10",
        "Id": 90,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.80864478",
        "level": 3,
        "lon": "123.4327909",
        "parentId": 23,
        "Pinyin": "shenyang",
        "precise": "0"
    },
    {
        "Name": "铁岭",
        "confIdence": "10",
        "Id": 101,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "42.29975701",
        "level": 3,
        "lon": "123.8548496",
        "parentId": 23,
        "Pinyin": "tieling",
        "precise": "0"
    },
    {
        "Name": "营口",
        "confIdence": "12",
        "Id": 97,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.66865107",
        "level": 3,
        "lon": "122.2333914",
        "parentId": 23,
        "Pinyin": "yingkou",
        "precise": "0"
    },
    {
        "Name": "包头",
        "confIdence": "10",
        "Id": 82,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.64711943",
        "level": 3,
        "lon": "109.8462385",
        "parentId": 22,
        "Pinyin": "baotou",
        "precise": "0"
    },
    {
        "Name": "巴彦淖尔",
        "confIdence": "10",
        "Id": 88,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.7691799",
        "level": 3,
        "lon": "107.4238067",
        "parentId": 22,
        "Pinyin": "bayannaoer",
        "precise": "0"
    },
    {
        "Name": "赤峰",
        "confIdence": "0",
        "Id": 84,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "42.29711232",
        "level": 3,
        "lon": "118.9307612",
        "parentId": 22,
        "Pinyin": "chifeng",
        "precise": "0"
    },
    {
        "Name": "鄂尔多斯",
        "confIdence": "0",
        "Id": 86,
        "FirstCharacter": "E",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.81648956",
        "level": 3,
        "lon": "109.9937063",
        "parentId": 22,
        "Pinyin": "eerduosi",
        "precise": "0"
    },
    {
        "Name": "呼和浩特",
        "confIdence": "10",
        "Id": 81,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.82831887",
        "level": 3,
        "lon": "111.6603505",
        "parentId": 22,
        "Pinyin": "huhehaote",
        "precise": "0"
    },
    {
        "Name": "呼伦贝尔",
        "confIdence": "0",
        "Id": 87,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "49.20163605",
        "level": 3,
        "lon": "119.7608218",
        "parentId": 22,
        "Pinyin": "hulunbeier",
        "precise": "0"
    },
    {
        "Name": "通辽",
        "confIdence": "0",
        "Id": 85,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "43.63375607",
        "level": 3,
        "lon": "122.2603633",
        "parentId": 22,
        "Pinyin": "tongliao",
        "precise": "0"
    },
    {
        "Name": "乌海",
        "confIdence": "14",
        "Id": 83,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.68317701",
        "level": 3,
        "lon": "106.8319991",
        "parentId": 22,
        "Pinyin": "wuhai",
        "precise": "0"
    },
    {
        "Name": "乌兰察布",
        "confIdence": "10",
        "Id": 89,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "41.02236295",
        "level": 3,
        "lon": "113.1128464",
        "parentId": 22,
        "Pinyin": "wulanchabu",
        "precise": "0"
    },
    {
        "Name": "固原",
        "confIdence": "12",
        "Id": 346,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.02152348",
        "level": 3,
        "lon": "106.285268",
        "parentId": 45,
        "Pinyin": "guyuan",
        "precise": "0"
    },
    {
        "Name": "石嘴山",
        "confIdence": "12",
        "Id": 344,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.02022328",
        "level": 3,
        "lon": "106.3793372",
        "parentId": 45,
        "Pinyin": "shizuishan",
        "precise": "0"
    },
    {
        "Name": "吴忠",
        "confIdence": "10",
        "Id": 345,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.993561",
        "level": 3,
        "lon": "106.2082542",
        "parentId": 45,
        "Pinyin": "wuzhong",
        "precise": "0"
    },
    {
        "Name": "银川",
        "confIdence": "12",
        "Id": 343,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.50262101",
        "level": 3,
        "lon": "106.2064786",
        "parentId": 45,
        "Pinyin": "yinchuan",
        "precise": "0"
    },
    {
        "Name": "中卫",
        "confIdence": "10",
        "Id": 347,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.52112419",
        "level": 3,
        "lon": "105.1967542",
        "parentId": 45,
        "Pinyin": "zhongwei",
        "precise": "0"
    },
    {
        "Name": "海东",
        "confIdence": "-1",
        "Id": 342,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.483629",
        "level": 3,
        "lon": "102.413413",
        "parentId": 44,
        "Pinyin": "haIdong",
        "precise": "-1"
    },
    {
        "Name": "西宁",
        "confIdence": "12",
        "Id": 341,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.64073861",
        "level": 3,
        "lon": "101.767921",
        "parentId": 44,
        "Pinyin": "xining",
        "precise": "0"
    },
    {
        "Name": "上海",
        "confIdence": "12",
        "Id": 50,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.24916171",
        "level": 3,
        "lon": "121.4878995",
        "parentId": 16,
        "Pinyin": "shanghai",
        "precise": "0"
    },
    {
        "Name": "长治",
        "confIdence": "12",
        "Id": 73,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.20166439",
        "level": 3,
        "lon": "113.1202921",
        "parentId": 21,
        "Pinyin": "changzhi",
        "precise": "0"
    },
    {
        "Name": "大同",
        "confIdence": "10",
        "Id": 71,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "40.1137445",
        "level": 3,
        "lon": "113.2905087",
        "parentId": 21,
        "Pinyin": "datong",
        "precise": "0"
    },
    {
        "Name": "晋城",
        "confIdence": "12",
        "Id": 74,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.49983447",
        "level": 3,
        "lon": "112.8673328",
        "parentId": 21,
        "Pinyin": "jincheng",
        "precise": "0"
    },
    {
        "Name": "晋中",
        "confIdence": "10",
        "Id": 76,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.69336153",
        "level": 3,
        "lon": "112.7385144",
        "parentId": 21,
        "Pinyin": "jinzhong",
        "precise": "0"
    },
    {
        "Name": "临汾",
        "confIdence": "10",
        "Id": 79,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.09974544",
        "level": 3,
        "lon": "111.5387876",
        "parentId": 21,
        "Pinyin": "linfen",
        "precise": "0"
    },
    {
        "Name": "吕梁",
        "confIdence": "10",
        "Id": 80,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.5273161",
        "level": 3,
        "lon": "111.1431566",
        "parentId": 21,
        "Pinyin": "lvliang",
        "precise": "0"
    },
    {
        "Name": "朔州",
        "confIdence": "12",
        "Id": 75,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.33767197",
        "level": 3,
        "lon": "112.4799277",
        "parentId": 21,
        "Pinyin": "shuozhou",
        "precise": "0"
    },
    {
        "Name": "太原",
        "confIdence": "12",
        "Id": 70,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.89027705",
        "level": 3,
        "lon": "112.5508636",
        "parentId": 21,
        "Pinyin": "taiyuan",
        "precise": "0"
    },
    {
        "Name": "忻州",
        "confIdence": "10",
        "Id": 78,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.46103057",
        "level": 3,
        "lon": "112.7279388",
        "parentId": 21,
        "Pinyin": "xinzhou",
        "precise": "0"
    },
    {
        "Name": "阳泉",
        "confIdence": "12",
        "Id": 72,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.86952949",
        "level": 3,
        "lon": "113.5692376",
        "parentId": 21,
        "Pinyin": "yangquan",
        "precise": "0"
    },
    {
        "Name": "运城",
        "confIdence": "12",
        "Id": 77,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.03885948",
        "level": 3,
        "lon": "111.0068537",
        "parentId": 21,
        "Pinyin": "yuncheng",
        "precise": "0"
    },
    {
        "Name": "滨州",
        "confIdence": "12",
        "Id": 199,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.40531394",
        "level": 3,
        "lon": "117.9682924",
        "parentId": 31,
        "Pinyin": "binzhou",
        "precise": "0"
    },
    {
        "Name": "东营",
        "confIdence": "12",
        "Id": 188,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.48712116",
        "level": 3,
        "lon": "118.5839263",
        "parentId": 31,
        "Pinyin": "dongying",
        "precise": "0"
    },
    {
        "Name": "德州",
        "confIdence": "10",
        "Id": 197,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.46082593",
        "level": 3,
        "lon": "116.3281614",
        "parentId": 31,
        "Pinyin": "dezhou",
        "precise": "0"
    },
    {
        "Name": "菏泽",
        "confIdence": "12",
        "Id": 200,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.2624405",
        "level": 3,
        "lon": "115.4633598",
        "parentId": 31,
        "Pinyin": "heze",
        "precise": "0"
    },
    {
        "Name": "济南",
        "confIdence": "12",
        "Id": 184,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.68278473",
        "level": 3,
        "lon": "117.0249671",
        "parentId": 31,
        "Pinyin": "jinan",
        "precise": "0"
    },
    {
        "Name": "济宁",
        "confIdence": "10",
        "Id": 191,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.40212166",
        "level": 3,
        "lon": "116.6007976",
        "parentId": 31,
        "Pinyin": "jining",
        "precise": "0"
    },
    {
        "Name": "莱芜",
        "confIdence": "14",
        "Id": 195,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.23365413",
        "level": 3,
        "lon": "117.6846669",
        "parentId": 31,
        "Pinyin": "laiwu",
        "precise": "0"
    },
    {
        "Name": "临沂",
        "confIdence": "10",
        "Id": 196,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.07240907",
        "level": 3,
        "lon": "118.3407682",
        "parentId": 31,
        "Pinyin": "linyi",
        "precise": "0"
    },
    {
        "Name": "聊城",
        "confIdence": "12",
        "Id": 198,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.45582851",
        "level": 3,
        "lon": "115.9868691",
        "parentId": 31,
        "Pinyin": "liaocheng",
        "precise": "0"
    },
    {
        "Name": "青岛",
        "confIdence": "10",
        "Id": 185,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.1052149",
        "level": 3,
        "lon": "120.3844282",
        "parentId": 31,
        "Pinyin": "qingdao",
        "precise": "0"
    },
    {
        "Name": "日照",
        "confIdence": "12",
        "Id": 194,
        "FirstCharacter": "R",
        "isFlag": 0,
        "isInland": 0,
        "lan": "35.42022519",
        "level": 3,
        "lon": "119.5071799",
        "parentId": 31,
        "Pinyin": "rizhao",
        "precise": "0"
    },
    {
        "Name": "泰安",
        "confIdence": "12",
        "Id": 192,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.18807776",
        "level": 3,
        "lon": "117.0894149",
        "parentId": 31,
        "Pinyin": "taian",
        "precise": "0"
    },
    {
        "Name": "潍坊",
        "confIdence": "10",
        "Id": 190,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.71611487",
        "level": 3,
        "lon": "119.1426338",
        "parentId": 31,
        "Pinyin": "weifang",
        "precise": "0"
    },
    {
        "Name": "威海",
        "confIdence": "12",
        "Id": 193,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.52878708",
        "level": 3,
        "lon": "122.0939584",
        "parentId": 31,
        "Pinyin": "weihai",
        "precise": "0"
    },
    {
        "Name": "烟台",
        "confIdence": "10",
        "Id": 189,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "37.53656156",
        "level": 3,
        "lon": "121.309555",
        "parentId": 31,
        "Pinyin": "yantai",
        "precise": "0"
    },
    {
        "Name": "淄博",
        "confIdence": "12",
        "Id": 186,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.80468485",
        "level": 3,
        "lon": "118.0591343",
        "parentId": 31,
        "Pinyin": "zibo",
        "precise": "0"
    },
    {
        "Name": "枣庄",
        "confIdence": "12",
        "Id": 187,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.80788308",
        "level": 3,
        "lon": "117.2793054",
        "parentId": 31,
        "Pinyin": "zaozhuang",
        "precise": "0"
    },
    {
        "Name": "巴中",
        "confIdence": "12",
        "Id": 298,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.86918916",
        "level": 3,
        "lon": "106.7579158",
        "parentId": 38,
        "Pinyin": "bazhong",
        "precise": "0"
    },
    {
        "Name": "成都",
        "confIdence": "12",
        "Id": 282,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.67994285",
        "level": 3,
        "lon": "104.0679235",
        "parentId": 38,
        "Pinyin": "chengdu",
        "precise": "0"
    },
    {
        "Name": "德阳",
        "confIdence": "12",
        "Id": 286,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.13113965",
        "level": 3,
        "lon": "104.4023978",
        "parentId": 38,
        "Pinyin": "deyang",
        "precise": "0"
    },
    {
        "Name": "达州",
        "confIdence": "10",
        "Id": 296,
        "FirstCharacter": "D",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.21419886",
        "level": 3,
        "lon": "107.4949734",
        "parentId": 38,
        "Pinyin": "dazhou",
        "precise": "0"
    },
    {
        "Name": "广元",
        "confIdence": "10",
        "Id": 288,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.44104016",
        "level": 3,
        "lon": "105.8196869",
        "parentId": 38,
        "Pinyin": "guangyuan",
        "precise": "0"
    },
    {
        "Name": "广安",
        "confIdence": "12",
        "Id": 295,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.46398389",
        "level": 3,
        "lon": "106.6357203",
        "parentId": 38,
        "Pinyin": "guangan",
        "precise": "0"
    },
    {
        "Name": "乐山",
        "confIdence": "12",
        "Id": 291,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.60095761",
        "level": 3,
        "lon": "103.7608242",
        "parentId": 38,
        "Pinyin": "leshan",
        "precise": "0"
    },
    {
        "Name": "绵阳",
        "confIdence": "10",
        "Id": 287,
        "FirstCharacter": "M",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.50470126",
        "level": 3,
        "lon": "104.705519",
        "parentId": 38,
        "Pinyin": "mianyang",
        "precise": "0"
    },
    {
        "Name": "眉山",
        "confIdence": "12",
        "Id": 293,
        "FirstCharacter": "M",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.06111508",
        "level": 3,
        "lon": "103.8414296",
        "parentId": 38,
        "Pinyin": "meishan",
        "precise": "0"
    },
    {
        "Name": "内江",
        "confIdence": "12",
        "Id": 290,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.59946153",
        "level": 3,
        "lon": "105.073056",
        "parentId": 38,
        "Pinyin": "neijiang",
        "precise": "0"
    },
    {
        "Name": "南充",
        "confIdence": "12",
        "Id": 292,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.80096517",
        "level": 3,
        "lon": "106.105554",
        "parentId": 38,
        "Pinyin": "nanchong",
        "precise": "0"
    },
    {
        "Name": "攀枝花",
        "confIdence": "12",
        "Id": 284,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.58757126",
        "level": 3,
        "lon": "101.7224232",
        "parentId": 38,
        "Pinyin": "panzhihua",
        "precise": "0"
    },
    {
        "Name": "遂宁",
        "confIdence": "12",
        "Id": 289,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.55749135",
        "level": 3,
        "lon": "105.5648878",
        "parentId": 38,
        "Pinyin": "suining",
        "precise": "0"
    },
    {
        "Name": "宜宾",
        "confIdence": "12",
        "Id": 294,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.7696748",
        "level": 3,
        "lon": "104.6330191",
        "parentId": 38,
        "Pinyin": "yibin",
        "precise": "0"
    },
    {
        "Name": "雅安",
        "confIdence": "10",
        "Id": 297,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.99971634",
        "level": 3,
        "lon": "103.0093565",
        "parentId": 38,
        "Pinyin": "yaan",
        "precise": "0"
    },
    {
        "Name": "自贡",
        "confIdence": "12",
        "Id": 283,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.35915689",
        "level": 3,
        "lon": "104.7760713",
        "parentId": 38,
        "Pinyin": "zigong",
        "precise": "0"
    },
    {
        "Name": "泸州",
        "confIdence": "12",
        "Id": 285,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.8959298",
        "level": 3,
        "lon": "105.4439703",
        "parentId": 38,
        "Pinyin": "zuozhou",
        "precise": "0"
    },
    {
        "Name": "资阳",
        "confIdence": "12",
        "Id": 299,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.13219143",
        "level": 3,
        "lon": "104.6359303",
        "parentId": 38,
        "Pinyin": "ziyang",
        "precise": "0"
    },
    {
        "Name": "安康",
        "confIdence": "10",
        "Id": 327,
        "FirstCharacter": "A",
        "isFlag": 0,
        "isInland": 0,
        "lan": "32.70437045",
        "level": 3,
        "lon": "109.0380446",
        "parentId": 42,
        "Pinyin": "ankang",
        "precise": "0"
    },
    {
        "Name": "宝鸡",
        "confIdence": "12",
        "Id": 321,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.36408081",
        "level": 3,
        "lon": "107.1706455",
        "parentId": 42,
        "Pinyin": "baoji",
        "precise": "0"
    },
    {
        "Name": "汉中",
        "confIdence": "10",
        "Id": 325,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.08156898",
        "level": 3,
        "lon": "107.0454776",
        "parentId": 42,
        "Pinyin": "hanzhong",
        "precise": "0"
    },
    {
        "Name": "商洛",
        "confIdence": "10",
        "Id": 328,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "33.8739074",
        "level": 3,
        "lon": "109.9342082",
        "parentId": 42,
        "Pinyin": "shangluo",
        "precise": "0"
    },
    {
        "Name": "铜川",
        "confIdence": "12",
        "Id": 320,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.9083677",
        "level": 3,
        "lon": "108.968067",
        "parentId": 42,
        "Pinyin": "tongchuan",
        "precise": "0"
    },
    {
        "Name": "渭南",
        "confIdence": "10",
        "Id": 323,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.50235798",
        "level": 3,
        "lon": "109.4839327",
        "parentId": 42,
        "Pinyin": "weinan",
        "precise": "0"
    },
    {
        "Name": "西安",
        "confIdence": "12",
        "Id": 319,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.2777999",
        "level": 3,
        "lon": "108.9530983",
        "parentId": 42,
        "Pinyin": "xian",
        "precise": "0"
    },
    {
        "Name": "咸阳",
        "confIdence": "12",
        "Id": 322,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "34.345373",
        "level": 3,
        "lon": "108.7075093",
        "parentId": 42,
        "Pinyin": "xianyang",
        "precise": "0"
    },
    {
        "Name": "延安",
        "confIdence": "10",
        "Id": 324,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "36.60332035",
        "level": 3,
        "lon": "109.5005098",
        "parentId": 42,
        "Pinyin": "yanan",
        "precise": "0"
    },
    {
        "Name": "榆林",
        "confIdence": "10",
        "Id": 326,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "38.27943924",
        "level": 3,
        "lon": "109.7459257",
        "parentId": 42,
        "Pinyin": "yulin",
        "precise": "0"
    },
    {
        "Name": "天津",
        "confIdence": "12",
        "Id": 51,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "39.1439299",
        "level": 3,
        "lon": "117.2108131",
        "parentId": 17,
        "Pinyin": "tianjin",
        "precise": "0"
    },
    {
        "Name": "高雄",
        "confIdence": "80",
        "Id": 58,
        "FirstCharacter": "G",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.626106",
        "level": 3,
        "lon": "120.326831",
        "parentId": 19,
        "Pinyin": "gaoxiong",
        "precise": "0"
    },
    {
        "Name": "台北",
        "confIdence": "80",
        "Id": 54,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.032375",
        "level": 3,
        "lon": "121.462864",
        "parentId": 19,
        "Pinyin": "taibei",
        "precise": "1"
    },
    {
        "Name": "桃园",
        "confIdence": "40",
        "Id": 55,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.003037",
        "level": 3,
        "lon": "121.300738",
        "parentId": 19,
        "Pinyin": "taoyuan",
        "precise": "0"
    },
    {
        "Name": "台中",
        "confIdence": "30",
        "Id": 56,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.172393",
        "level": 3,
        "lon": "120.663732",
        "parentId": 19,
        "Pinyin": "taizhong",
        "precise": "0"
    },
    {
        "Name": "台南",
        "confIdence": "30",
        "Id": 57,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.000278",
        "level": 3,
        "lon": "120.187702",
        "parentId": 19,
        "Pinyin": "tainan",
        "precise": "0"
    },
    {
        "Name": "新北",
        "confIdence": "-1",
        "Id": 53,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.065228",
        "level": 3,
        "lon": "121.53407",
        "parentId": 19,
        "Pinyin": "xinbei",
        "precise": "-1"
    },
    {
        "Name": "香港",
        "confIdence": "14",
        "Id": 47,
        "FirstCharacter": "X",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.29358599",
        "level": 3,
        "lon": "114.1861241",
        "parentId": 13,
        "Pinyin": "xianggang",
        "precise": "0"
    },
    {
        "Name": "昌都",
        "confIdence": "0",
        "Id": 316,
        "FirstCharacter": "C",
        "isFlag": 0,
        "isInland": 0,
        "lan": "31.14057563",
        "level": 3,
        "lon": "97.18558158",
        "parentId": 41,
        "Pinyin": "changdu",
        "precise": "0"
    },
    {
        "Name": "拉萨",
        "confIdence": "10",
        "Id": 314,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.66255706",
        "level": 3,
        "lon": "91.1118909",
        "parentId": 41,
        "Pinyin": "lasa",
        "precise": "0"
    },
    {
        "Name": "林芝",
        "confIdence": "0",
        "Id": 317,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.66694063",
        "level": 3,
        "lon": "94.34998546",
        "parentId": 41,
        "Pinyin": "linzhi",
        "precise": "0"
    },
    {
        "Name": "日喀则",
        "confIdence": "12",
        "Id": 315,
        "FirstCharacter": "R",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.26816003",
        "level": 3,
        "lon": "88.95606277",
        "parentId": 41,
        "Pinyin": "rikaze",
        "precise": "0"
    },
    {
        "Name": "山南",
        "confIdence": "-1",
        "Id": 318,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.244492",
        "level": 3,
        "lon": "91.765273",
        "parentId": 41,
        "Pinyin": "shannan",
        "precise": "-1"
    },
    {
        "Name": "哈密",
        "confIdence": "0",
        "Id": 351,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "42.3444671",
        "level": 3,
        "lon": "93.52937301",
        "parentId": 46,
        "Pinyin": "hami",
        "precise": "0"
    },
    {
        "Name": "克拉玛依",
        "confIdence": "10",
        "Id": 349,
        "FirstCharacter": "K",
        "isFlag": 0,
        "isInland": 0,
        "lan": "45.59433107",
        "level": 3,
        "lon": "84.88118019",
        "parentId": 46,
        "Pinyin": "kelamayi",
        "precise": "0"
    },
    {
        "Name": "吐鲁番",
        "confIdence": "10",
        "Id": 350,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "42.67892482",
        "level": 3,
        "lon": "89.26602549",
        "parentId": 46,
        "Pinyin": "tulufan",
        "precise": "0"
    },
    {
        "Name": "乌鲁木齐",
        "confIdence": "10",
        "Id": 348,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "43.84038035",
        "level": 3,
        "lon": "87.56498774",
        "parentId": 46,
        "Pinyin": "wulumuqi",
        "precise": "0"
    },
    {
        "Name": "保山",
        "confIdence": "10",
        "Id": 309,
        "FirstCharacter": "B",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.1204892",
        "level": 3,
        "lon": "99.17799561",
        "parentId": 40,
        "Pinyin": "baoshan",
        "precise": "0"
    },
    {
        "Name": "昆明",
        "confIdence": "10",
        "Id": 306,
        "FirstCharacter": "K",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.0491531",
        "level": 3,
        "lon": "102.7146011",
        "parentId": 40,
        "Pinyin": "kunming",
        "precise": "0"
    },
    {
        "Name": "丽江",
        "confIdence": "10",
        "Id": 311,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "26.87535109",
        "level": 3,
        "lon": "100.2296284",
        "parentId": 40,
        "Pinyin": "lijiang",
        "precise": "0"
    },
    {
        "Name": "临沧",
        "confIdence": "10",
        "Id": 313,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "23.8878061",
        "level": 3,
        "lon": "100.0926129",
        "parentId": 40,
        "Pinyin": "lincang",
        "precise": "0"
    },
    {
        "Name": "普洱",
        "confIdence": "10",
        "Id": 312,
        "FirstCharacter": "P",
        "isFlag": 0,
        "isInland": 0,
        "lan": "22.78877778",
        "level": 3,
        "lon": "100.9800577",
        "parentId": 40,
        "Pinyin": "puer",
        "precise": "0"
    },
    {
        "Name": "曲靖",
        "confIdence": "10",
        "Id": 307,
        "FirstCharacter": "Q",
        "isFlag": 0,
        "isInland": 0,
        "lan": "25.52075814",
        "level": 3,
        "lon": "103.7825389",
        "parentId": 40,
        "Pinyin": "qujing",
        "precise": "0"
    },
    {
        "Name": "玉溪",
        "confIdence": "10",
        "Id": 308,
        "FirstCharacter": "Y",
        "isFlag": 0,
        "isInland": 0,
        "lan": "24.37044713",
        "level": 3,
        "lon": "102.5450679",
        "parentId": 40,
        "Pinyin": "yuxi",
        "precise": "0"
    },
    {
        "Name": "昭通",
        "confIdence": "10",
        "Id": 310,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "27.34063296",
        "level": 3,
        "lon": "103.7250207",
        "parentId": 40,
        "Pinyin": "zhaotong",
        "precise": "0"
    },
    {
        "Name": "重庆",
        "confIdence": "0",
        "Id": 52,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.54460611",
        "level": 3,
        "lon": "106.530635",
        "parentId": 18,
        "Pinyin": "zhongqing",
        "precise": "0"
    },
    {
        "Name": "杭州",
        "confIdence": "10",
        "Id": 137,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.25924446",
        "level": 3,
        "lon": "120.2193754",
        "parentId": 27,
        "Pinyin": "hangzhou",
        "precise": "0"
    },
    {
        "Name": "湖州",
        "confIdence": "12",
        "Id": 141,
        "FirstCharacter": "H",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.87792516",
        "level": 3,
        "lon": "120.1372432",
        "parentId": 27,
        "Pinyin": "huzhou",
        "precise": "0"
    },
    {
        "Name": "嘉兴",
        "confIdence": "12",
        "Id": 140,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.77399224",
        "level": 3,
        "lon": "120.7604277",
        "parentId": 27,
        "Pinyin": "jiaxing",
        "precise": "0"
    },
    {
        "Name": "金华",
        "confIdence": "12",
        "Id": 143,
        "FirstCharacter": "J",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.10289911",
        "level": 3,
        "lon": "119.6525757",
        "parentId": 27,
        "Pinyin": "jinhua",
        "precise": "0"
    },
    {
        "Name": "丽水",
        "confIdence": "12",
        "Id": 147,
        "FirstCharacter": "L",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.45629955",
        "level": 3,
        "lon": "119.9295758",
        "parentId": 27,
        "Pinyin": "lishui",
        "precise": "0"
    },
    {
        "Name": "宁波",
        "confIdence": "12",
        "Id": 138,
        "FirstCharacter": "N",
        "isFlag": 0,
        "isInland": 0,
        "lan": "29.88525897",
        "level": 3,
        "lon": "121.579006",
        "parentId": 27,
        "Pinyin": "ningbo",
        "precise": "0"
    },
    {
        "Name": "绍兴",
        "confIdence": "12",
        "Id": 142,
        "FirstCharacter": "S",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.00236458",
        "level": 3,
        "lon": "120.5924674",
        "parentId": 27,
        "Pinyin": "shaoxing",
        "precise": "0"
    },
    {
        "Name": "台州",
        "confIdence": "12",
        "Id": 146,
        "FirstCharacter": "T",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.66828329",
        "level": 3,
        "lon": "121.4406129",
        "parentId": 27,
        "Pinyin": "taizhou",
        "precise": "0"
    },
    {
        "Name": "温州",
        "confIdence": "12",
        "Id": 139,
        "FirstCharacter": "W",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.00283759",
        "level": 3,
        "lon": "120.6906347",
        "parentId": 27,
        "Pinyin": "wenzhou",
        "precise": "0"
    },
    {
        "Name": "衢州",
        "confIdence": "12",
        "Id": 144,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "28.95691045",
        "level": 3,
        "lon": "118.8758417",
        "parentId": 27,
        "Pinyin": "zuozhou",
        "precise": "0"
    },
    {
        "Name": "舟山",
        "confIdence": "12",
        "Id": 145,
        "FirstCharacter": "Z",
        "isFlag": 0,
        "isInland": 0,
        "lan": "30.0360103",
        "level": 3,
        "lon": "122.1698721",
        "parentId": 27,
        "Pinyin": "zhoushan",
        "precise": "0"
    }
]